version: "3"

services:
  wq-rabbitmq:
    image: rabbitmq
    container_name: wq-rabbitmq
    restart: always
    networks:
      - wq-network
    ports:
      - 5672:5672
      - 15672:15672

  wq-consumer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wq-consumer
    volumes:
      - ./:/code
    restart: unless-stopped
    command: >
      bash -c "python -u consumer.py"
    networks:
      - wq-network
    depends_on:
      - wq-rabbitmq

  wq-producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wq-producer
    volumes:
      - ./:/code
    restart: unless-stopped
    command: >
      bash -c "python -u producer.py"
    networks:
      - wq-network
    depends_on:
      - wq-rabbitmq


networks:
  wq-network:
    driver: bridge
